const DB_KEY='cormach-maps-project-v1';
let project={version:1,updatedAt:null,clients:{},imports:{}};
let map,markers=L.layerGroup(),deferredPrompt,currentId=null;
const $=s=>document.querySelector(s);
const euro=n=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(Number(n)||0);
const norm=s=>String(s??'').trim();
const num=v=>{const n=Number(String(v??0).replace(',','.'));return Number.isFinite(n)?n:0};
const excelDate=v=>{if(!v)return'';if(typeof v==='number'){const d=XLSX.SSF.parse_date_code(v);return d?`${String(d.d).padStart(2,'0')}/${String(d.m).padStart(2,'0')}/${d.y}`:''}return String(v)};
function save(){project.updatedAt=new Date().toISOString();localStorage.setItem(DB_KEY,JSON.stringify(project));render()}
function load(){try{const p=JSON.parse(localStorage.getItem(DB_KEY));if(p?.clients){project=p;for(const c of Object.values(project.clients)){c.orderLines??=[];c.saleLines??=[];c.saleYears??={}}}}catch(e){console.warn(e)}}
function initMap(){map=L.map('map').setView([42.5,12.5],6);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);markers.addTo(map)}
function rowsFromSheet(ws){return XLSX.utils.sheet_to_json(ws,{defval:'',raw:true})}
function findType(headers){const h=headers.map(x=>x.toUpperCase());if(h.includes('RAGIONE SOCIALE 1')&&h.includes('INDIRIZZO')&&h.includes('CITTA'))return'clienti';if(h.includes('IMPORTO INEVASO'))return'ordini';if(h.includes('IMPORTO CONSEGNATO'))return'vendite';return null}
async function importFiles(files){for(const file of files){const data=await file.arrayBuffer();const wb=XLSX.read(data,{type:'array'});for(const name of wb.SheetNames){const rows=rowsFromSheet(wb.Sheets[name]);if(!rows.length)continue;const type=findType(Object.keys(rows[0]));if(!type)continue;if(type==='clienti')importClients(rows);if(type==='ordini')importOrders(rows);if(type==='vendite')importSales(rows);project.imports[type]={file:file.name,rows:rows.length,date:new Date().toISOString()}}}save();$('#status').textContent=statusText()}
function ensure(id,name=''){id=norm(id).padStart(5,'0');if(!id)return null;return project.clients[id]??=( {id,name,emails:[],phones:[],orders:0,sales:0,orderLines:[],saleLines:[],saleYears:{},note:'',lat:null,lng:null,manualPosition:false} )}
function importClients(rows){const seen=new Set();for(const r of rows){const id=norm(r['CLIENTE']).padStart(5,'0');if(!id)continue;const c=ensure(id,norm(r['RAGIONE SOCIALE 1']));c.name=norm(r['RAGIONE SOCIALE 1'])||c.name;c.address=norm(r['INDIRIZZO']);c.city=norm(r['CITTA']);c.cap=norm(r['CAP']).padStart(5,'0');c.province=norm(r['PROVINCIA']);c.agentCode=norm(r['AGENTE']);c.agent=norm(r['DESCRIZIONE ELEMENTO_2']||r['DESCRIZIONE ELEMENTO']);c.abc=norm(r['CLASSE ABC']);c.payment=norm(r['DESCRIZIONE ELEMENTO']);[r['NR.TELEFONICO'],r['NR.CELLULARE']].map(norm).filter(Boolean).forEach(x=>{if(!c.phones.includes(x))c.phones.push(x)});const em=norm(r['EMAIL']);if(em&&!c.emails.includes(em))c.emails.push(em);seen.add(id)}project.imports.clientiCount=seen.size}
function importOrders(rows){for(const c of Object.values(project.clients)){c.orders=0;c.orderLines=[]}for(const r of rows){const c=ensure(r['CLIENTE'],r['CLIENTE']);if(!c)continue;const amount=num(r['IMPORTO INEVASO']);c.orders+=amount;c.orderLines.push({order:norm(r['NUM.']),date:excelDate(r['DATA CREAZIONE']),delivery:excelDate(r['DATA CONSEGNA']),article:norm(r['ARTICOLO']),description:norm(r['DESCRIZIONE']),qty:num(r['QTA INEVASA']),amount})}}
function importSales(rows){for(const c of Object.values(project.clients)){c.sales=0;c.saleYears={};c.saleLines=[]}for(const r of rows){const c=ensure(r['CLIENTE'],r['RAGIONE SOCIALE 1']);if(!c)continue;const amount=num(r['IMPORTO CONSEGNATO']);const year=norm(r['ANNO SPEDIZIONE']);c.sales+=amount;c.saleYears[year]=(c.saleYears[year]||0)+amount;c.saleLines.push({shipment:norm(r['NUMERO SPEDIZIONE']),date:excelDate(r['DATA SPEDIZIONE']),year,article:norm(r['ARTICOLO']),description:norm(r['DESCRIZIONE']),qty:num(r['QTA CONSEGNATA']),amount})}}
function statusText(){const x=project.imports;return ['clienti','ordini','vendite'].map(k=>x[k]?`${k}: ${x[k].rows} righe`:`${k}: non importato`).join(' · ')}
function selectedYears(){const from=num($('#yearFrom').value)||-Infinity,to=num($('#yearTo').value)||Infinity;return{from,to}}
function lineYear(line){if(line.year)return num(line.year);const m=String(line.date||'').match(/(\d{4})$/);return m?num(m[1]):0}
function matchingLines(c){const q=norm($('#productSearch').value).toLowerCase(),source=$('#movementFilter').value,{from,to}=selectedYears();let lines=[];if(source!=='orders')lines.push(...(c.saleLines||[]).map(x=>({...x,kind:'sale'})));if(source!=='sales')lines.push(...(c.orderLines||[]).map(x=>({...x,kind:'order'})));return lines.filter(x=>{const y=lineYear(x),product=!q||`${x.article} ${x.description}`.toLowerCase().includes(q),period=y>=from&&y<=to;return product&&period})}
function hasTransactionFilter(){return norm($('#productSearch').value)||$('#yearFrom').value||$('#yearTo').value||$('#movementFilter').value!=='both'}
function filtered(){const q=norm($('#search').value).toLowerCase(),ag=$('#agentFilter').value,pr=$('#provinceFilter').value;return Object.values(project.clients).filter(c=>(!q||[c.name,c.city,c.province,c.id].join(' ').toLowerCase().includes(q))&&(!ag||c.agent===ag)&&(!pr||c.province===pr)&&(!$('#onlyOrders').checked||c.orders>0)&&(!$('#onlySales').checked||c.sales>0)&&(!$('#onlyMissing').checked||c.lat==null)&&(!hasTransactionFilter()||matchingLines(c).length>0))}
function updateProductSuggestions(){const q=norm($('#productSearch').value).toLowerCase(),seen=new Map();for(const c of Object.values(project.clients)){for(const x of [...(c.saleLines||[]),...(c.orderLines||[])]){const label=[x.article,x.description].filter(Boolean).join(' — ');if(label&&(!q||label.toLowerCase().includes(q)))seen.set(label,label)}}$('#productSuggestions').innerHTML=[...seen.values()].slice(0,250).map(v=>`<option value="${escapeHtml(v)}"></option>`).join('')}
function updateYears(){const years=new Set();for(const c of Object.values(project.clients)){for(const x of [...(c.saleLines||[]),...(c.orderLines||[])]){const y=lineYear(x);if(y)years.add(y)}}const vals=[...years].sort((a,b)=>b-a);for(const id of ['yearFrom','yearTo']){const el=$(`#${id}`),cur=el.value,label=id==='yearFrom'?'Da anno':'A anno';el.innerHTML=`<option value="">${label}</option>`+vals.map(y=>`<option value="${y}">${y}</option>`).join('');el.value=cur}}
function render(){const all=Object.values(project.clients),view=filtered();fillSelect('#agentFilter',[...new Set(all.map(c=>c.agent).filter(Boolean))]);fillSelect('#provinceFilter',[...new Set(all.map(c=>c.province).filter(Boolean))]);updateYears();updateProductSuggestions();const visibleLines=view.flatMap(matchingLines);const filteredSales=visibleLines.filter(x=>x.kind==='sale').reduce((s,x)=>s+x.amount,0),filteredOrders=visibleLines.filter(x=>x.kind==='order').reduce((s,x)=>s+x.amount,0);$('#clientCount').textContent=view.length;$('#mappedCount').textContent=view.filter(c=>c.lat!=null).length;$('#ordersTotal').textContent=euro(hasTransactionFilter()?filteredOrders:view.reduce((s,c)=>s+c.orders,0));$('#salesTotal').textContent=euro(hasTransactionFilter()?filteredSales:view.reduce((s,c)=>s+c.sales,0));$('#status').textContent=statusText();renderList(view);renderMarkers(view)}
function fillSelect(sel,vals){const el=$(sel),cur=el.value,label=el.options[0].text;el.innerHTML=`<option value="">${label}</option>`+vals.sort().map(v=>`<option>${escapeHtml(v)}</option>`).join('');el.value=cur}
function renderList(items){$('#list').innerHTML=items.slice(0,400).map(c=>{const lines=matchingLines(c),fs=lines.filter(x=>x.kind==='sale').reduce((s,x)=>s+x.amount,0),fo=lines.filter(x=>x.kind==='order').reduce((s,x)=>s+x.amount,0);return `<article class="client" data-id="${c.id}"><h3>${escapeHtml(c.name||c.id)}</h3><p>${escapeHtml([c.city,c.province,c.agent].filter(Boolean).join(' · '))}</p><div class="badges">${(hasTransactionFilter()?fo:c.orders)?`<span class="badge order">Ordini ${euro(hasTransactionFilter()?fo:c.orders)}</span>`:''}${(hasTransactionFilter()?fs:c.sales)?`<span class="badge sales">Vendite ${euro(hasTransactionFilter()?fs:c.sales)}</span>`:''}${hasTransactionFilter()?`<span class="badge">${lines.length} righe prodotto</span>`:''}${c.lat==null?'<span class="badge missing">Da geocodificare</span>':''}</div></article>`}).join('');document.querySelectorAll('.client').forEach(x=>x.onclick=()=>openDetail(x.dataset.id))}
function renderMarkers(items){markers.clearLayers();for(const c of items){if(c.lat==null)continue;const cls=c.orders>0?'order':c.sales>50000?'top':'';const icon=L.divIcon({className:'',html:`<div class="marker-dot ${cls}"></div>`,iconSize:[18,18],iconAnchor:[9,9]});const m=L.marker([c.lat,c.lng],{icon,draggable:true}).addTo(markers).bindTooltip(c.name||c.id);m.on('click',()=>openDetail(c.id));m.on('dragend',e=>{const p=e.target.getLatLng();c.lat=p.lat;c.lng=p.lng;c.manualPosition=true;save()})}}
function openDetail(id){currentId=id;const c=project.clients[id];const years=Object.entries(c.saleYears||{}).sort((a,b)=>b[0]-a[0]).map(([y,v])=>`${y}: ${euro(v)}`).join('<br>')||'—';$('#detail').innerHTML=`<h2>${escapeHtml(c.name||c.id)}</h2><p>${escapeHtml([c.address,c.cap,c.city,c.province].filter(Boolean).join(', '))}</p><div class="detail-grid"><div class="detail-box"><b>${euro(c.orders)}</b><span>Ordini aperti</span></div><div class="detail-box"><b>${euro(c.sales)}</b><span>Vendite totali</span></div><div class="detail-box"><b>${escapeHtml(c.agent||'—')}</b><span>Agente</span></div><div class="detail-box"><b>${years}</b><span>Vendite per anno</span></div></div><div class="field"><label>Coordinate</label><div class="row"><input id="lat" value="${c.lat??''}" placeholder="Latitudine"><input id="lng" value="${c.lng??''}" placeholder="Longitudine"></div></div><div class="field"><label>Note locali</label><textarea id="note">${escapeHtml(c.note||'')}</textarea></div><div class="detail-actions"><button type="button" id="saveDetail" class="primary">Salva</button><a class="button" target="_blank" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(c.lat!=null?`${c.lat},${c.lng}`:[c.address,c.city,c.province].join(' '))}">Naviga</a></div><p><small>${c.phones?.map(escapeHtml).join(' · ')||''}<br>${c.emails?.map(escapeHtml).join(' · ')||''}</small></p>`;$('#saveDetail').onclick=()=>{const lat=parseFloat($('#lat').value),lng=parseFloat($('#lng').value);c.lat=Number.isFinite(lat)?lat:null;c.lng=Number.isFinite(lng)?lng:null;c.manualPosition=Number.isFinite(lat)&&Number.isFinite(lng);c.note=$('#note').value;save();$('#detailDialog').close()};$('#detailDialog').showModal()}
async function geocodeMissing(){const list=filtered().filter(c=>c.lat==null&&c.address&&c.city);if(!list.length)return alert('Nessun cliente da geocodificare nel filtro corrente.');if(!confirm(`Geocodificare ${list.length} indirizzi? Il servizio pubblico richiede circa un secondo per indirizzo.`))return;let done=0;for(const c of list){$('#status').textContent=`Geocodifica ${done+1}/${list.length}: ${c.name}`;try{const q=[c.address,c.cap,c.city,c.province,'Italia'].filter(Boolean).join(', ');const res=await fetch(`https://nominatim.openstreetmap.org/search?format=json&limit=1&countrycodes=it&q=${encodeURIComponent(q)}`,{headers:{'Accept-Language':'it'}});const data=await res.json();if(data[0]){c.lat=Number(data[0].lat);c.lng=Number(data[0].lon)}}catch(e){console.warn(e)}done++;localStorage.setItem(DB_KEY,JSON.stringify(project));renderMarkers(filtered());await new Promise(r=>setTimeout(r,1100))}save();alert(`Geocodifica completata: ${done} indirizzi elaborati.`)}
function exportProject(){const blob=new Blob([JSON.stringify(project,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`cormach-maps-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
function fit(){const pts=filtered().filter(c=>c.lat!=null).map(c=>[c.lat,c.lng]);if(pts.length)map.fitBounds(pts,{padding:[30,30]})}
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
$('#excelInput').onchange=e=>importFiles([...e.target.files]);$('#projectInput').onchange=async e=>{try{const p=JSON.parse(await e.target.files[0].text());if(!p.clients)throw 0;project=p;save();fit()}catch{alert('Progetto non valido')}};$('#exportBtn').onclick=exportProject;$('#fitBtn').onclick=fit;$('#geocodeBtn').onclick=geocodeMissing;['search','productSearch','agentFilter','provinceFilter','movementFilter','yearFrom','yearTo','onlyOrders','onlySales','onlyMissing'].forEach(id=>$(`#${id}`).addEventListener(['search','productSearch'].includes(id)?'input':'change',render));window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{deferredPrompt?.prompt();deferredPrompt=null;$('#installBtn').hidden=true};
load();initMap();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
