const DB_KEY='maps-app-project-v2';
let project={version:2,updatedAt:null,clients:{},imports:{}};
let map=null,markers=null,deferredPrompt,currentId=null;
const $=s=>document.querySelector(s);
const euro=n=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(Number(n)||0);
const norm=s=>String(s??'').trim();
const num=v=>{if(typeof v==='number')return Number.isFinite(v)?v:0;const s=String(v??'').trim().replace(/\./g,'').replace(',','.');const n=Number(s);return Number.isFinite(n)?n:0};
const excelDate=v=>{if(!v)return'';if(typeof v==='number'||/^\d+(\.\d+)?$/.test(String(v))){const n=Number(v);const d=new Date(Date.UTC(1899,11,30)+n*86400000);return `${String(d.getUTCDate()).padStart(2,'0')}/${String(d.getUTCMonth()+1).padStart(2,'0')}/${d.getUTCFullYear()}`}return String(v)};
function save(){project.updatedAt=new Date().toISOString();localStorage.setItem(DB_KEY,JSON.stringify(project));render()}
function load(){try{const p=JSON.parse(localStorage.getItem(DB_KEY));if(p?.clients){project=p;for(const c of Object.values(project.clients)){c.orderLines??=[];c.saleLines??=[];c.saleYears??={}}}}catch(e){console.warn(e)}}
function initMap(){if(typeof L==='undefined'){document.getElementById('map').innerHTML='<div style="padding:24px;text-align:center"><b>Mappa non disponibile.</b><br><small>Serve una connessione Internet per caricare la cartografia. L’importazione Excel funziona comunque.</small></div>';return}map=L.map('map').setView([42.5,12.5],6);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);markers=L.layerGroup().addTo(map)}
function xmlText(node){return [...node.getElementsByTagNameNS('*','t')].map(x=>x.textContent||'').join('')}
function colIndex(ref){const m=String(ref).match(/[A-Z]+/);if(!m)return 0;let n=0;for(const ch of m[0])n=n*26+ch.charCodeAt(0)-64;return n-1}
async function readXlsx(file){if(typeof JSZip==='undefined')throw new Error('Lettore Excel non disponibile');const zip=await JSZip.loadAsync(await file.arrayBuffer());const parser=new DOMParser();let shared=[];const ss=zip.file('xl/sharedStrings.xml');if(ss){const doc=parser.parseFromString(await ss.async('string'),'application/xml');shared=[...doc.getElementsByTagNameNS('*','si')].map(xmlText)}const wbDoc=parser.parseFromString(await zip.file('xl/workbook.xml').async('string'),'application/xml');const relDoc=parser.parseFromString(await zip.file('xl/_rels/workbook.xml.rels').async('string'),'application/xml');const rels={};for(const r of relDoc.getElementsByTagNameNS('*','Relationship'))rels[r.getAttribute('Id')]=r.getAttribute('Target');const sheets=[];for(const s of wbDoc.getElementsByTagNameNS('*','sheet')){const rid=s.getAttributeNS('http://schemas.openxmlformats.org/officeDocument/2006/relationships','id')||s.getAttribute('r:id');let target=rels[rid];if(!target)continue;target=target.replace(/^\//,'');if(!target.startsWith('xl/'))target='xl/'+target.replace(/^\.\.\//,'');sheets.push({name:s.getAttribute('name'),target})}const all=[];for(const sh of sheets){const f=zip.file(sh.target);if(!f)continue;const doc=parser.parseFromString(await f.async('string'),'application/xml');const matrix=[];for(const row of doc.getElementsByTagNameNS('*','row')){const arr=[];for(const c of row.getElementsByTagNameNS('*','c')){const idx=colIndex(c.getAttribute('r'));const t=c.getAttribute('t');let v='';const vn=c.getElementsByTagNameNS('*','v')[0];if(t==='inlineStr')v=xmlText(c);else if(vn){v=vn.textContent||'';if(t==='s')v=shared[Number(v)]??'';else if(t==='b')v=v==='1';else if(v!==''&&!isNaN(v))v=Number(v)}arr[idx]=v}matrix.push(arr)}if(matrix.length)all.push({name:sh.name,rows:matrix})}return all}
function uniqueHeaders(raw){const used={};return raw.map((x,i)=>{let h=norm(x)||`COL_${i+1}`;used[h]=(used[h]||0)+1;return used[h]===1?h:`${h}_${used[h]-1}`})}
function matrixToObjects(matrix){if(!matrix.length)return[];const headers=uniqueHeaders(matrix[0]);return matrix.slice(1).filter(r=>r.some(v=>norm(v)!=='')).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??''])))}
function findType(headers){const h=headers.map(x=>x.toUpperCase());if(h.includes('RAGIONE SOCIALE 1')&&h.includes('INDIRIZZO')&&h.includes('CITTA'))return'clienti';if(h.includes('IMPORTO INEVASO'))return'ordini';if(h.includes('IMPORTO CONSEGNATO'))return'vendite';return null}
async function importFiles(files){if(!files.length)return;const status=$('#status');let imported=0,errors=[];status.textContent='Lettura Excel in corso…';for(const file of files){try{const sheets=await readXlsx(file);let recognized=false;for(const sh of sheets){const rows=matrixToObjects(sh.rows);if(!rows.length)continue;const type=findType(Object.keys(rows[0]));if(!type)continue;recognized=true;if(type==='clienti')importClients(rows);if(type==='ordini')importOrders(rows);if(type==='vendite')importSales(rows);project.imports[type]={file:file.name,rows:rows.length,date:new Date().toISOString()};imported++}if(!recognized)errors.push(`${file.name}: struttura non riconosciuta`)}catch(e){console.error(e);errors.push(`${file.name}: ${e.message||'errore di lettura'}`)}}save();status.textContent=statusText();if(errors.length)alert(`Importazione completata con avvisi:\n\n${errors.join('\n')}`);else alert(`Importazione completata. File riconosciuti: ${imported}.`);$('#excelInput').value=''}
function ensure(id,name=''){id=norm(id).padStart(5,'0');if(!id||id==='00000')return null;return project.clients[id]??={id,name,emails:[],phones:[],orders:0,sales:0,orderLines:[],saleLines:[],saleYears:{},note:'',lat:null,lng:null,manualPosition:false}}
function importClients(rows){const seen=new Set();for(const r of rows){const id=norm(r['CLIENTE']).padStart(5,'0');if(!id||id==='00000')continue;const c=ensure(id,norm(r['RAGIONE SOCIALE 1']));c.name=norm(r['RAGIONE SOCIALE 1'])||c.name;c.address=norm(r['INDIRIZZO']);c.city=norm(r['CITTA']);c.cap=norm(r['CAP']).padStart(5,'0');c.province=norm(r['PROVINCIA']);c.agentCode=norm(r['AGENTE']);c.agent=norm(r['DESCRIZIONE ELEMENTO_2']||r['DESCRIZIONE ELEMENTO_1']||r['DESCRIZIONE ELEMENTO']);c.abc=norm(r['CLASSE ABC']);c.payment=norm(r['DESCRIZIONE ELEMENTO']);[r['NR.TELEFONICO'],r['NR.CELLULARE']].map(norm).filter(Boolean).forEach(x=>{if(!c.phones.includes(x))c.phones.push(x)});const em=norm(r['EMAIL']);if(em&&!c.emails.includes(em))c.emails.push(em);seen.add(id)}project.imports.clientiCount=seen.size}
function importOrders(rows){for(const c of Object.values(project.clients)){c.orders=0;c.orderLines=[]}for(const r of rows){const c=ensure(r['CLIENTE'],r['CLIENTE_1']);if(!c)continue;const amount=num(r['IMPORTO INEVASO']);c.name=c.name||norm(r['CLIENTE_1']);c.orders+=amount;c.orderLines.push({order:norm(r['NUM.']),date:excelDate(r['DATA CREAZIONE']),delivery:excelDate(r['DATA CONSEGNA']),year:norm(r['ANNO']),article:norm(r['ARTICOLO']),description:norm(r['DESCRIZIONE']),qty:num(r['QTA INEVASA']),amount})}}
function importSales(rows){for(const c of Object.values(project.clients)){c.sales=0;c.saleYears={};c.saleLines=[]}for(const r of rows){const c=ensure(r['CLIENTE'],r['RAGIONE SOCIALE 1']);if(!c)continue;const amount=num(r['IMPORTO CONSEGNATO']);const year=norm(r['ANNO SPEDIZIONE']);c.name=c.name||norm(r['RAGIONE SOCIALE 1']);c.sales+=amount;c.saleYears[year]=(c.saleYears[year]||0)+amount;c.saleLines.push({shipment:norm(r['NUMERO SPEDIZIONE']),date:excelDate(r['DATA SPEDIZIONE']),year,article:norm(r['ARTICOLO']),description:norm(r['DESCRIZIONE']),qty:num(r['QTA CONSEGNATA']),amount})}}
function statusText(){const x=project.imports;return ['clienti','ordini','vendite'].map(k=>x[k]?`${k}: ${x[k].rows} righe`:`${k}: non importato`).join(' · ')}
function selectedYears(){const from=num($('#yearFrom').value)||-Infinity,to=num($('#yearTo').value)||Infinity;return{from,to}}
function lineYear(line){if(line.year)return num(line.year);const m=String(line.date||'').match(/(\d{4})$/);return m?num(m[1]):0}
function matchingLines(c){const q=norm($('#productSearch').value).toLowerCase(),source=$('#movementFilter').value,{from,to}=selectedYears();let lines=[];if(source!=='orders')lines.push(...(c.saleLines||[]).map(x=>({...x,kind:'sale'})));if(source!=='sales')lines.push(...(c.orderLines||[]).map(x=>({...x,kind:'order'})));return lines.filter(x=>{const y=lineYear(x);return(!q||`${x.article} ${x.description}`.toLowerCase().includes(q))&&y>=from&&y<=to})}
function hasTransactionFilter(){return norm($('#productSearch').value)||$('#yearFrom').value||$('#yearTo').value||$('#movementFilter').value!=='both'}
function filtered(){const q=norm($('#search').value).toLowerCase(),ag=$('#agentFilter').value,pr=$('#provinceFilter').value;return Object.values(project.clients).filter(c=>(!q||[c.name,c.city,c.province,c.id].join(' ').toLowerCase().includes(q))&&(!ag||c.agent===ag)&&(!pr||c.province===pr)&&(!$('#onlyOrders').checked||c.orders>0)&&(!$('#onlySales').checked||c.sales>0)&&(!$('#onlyMissing').checked||c.lat==null)&&(!hasTransactionFilter()||matchingLines(c).length>0))}
function updateProductSuggestions(){const q=norm($('#productSearch').value).toLowerCase(),seen=new Map();for(const c of Object.values(project.clients))for(const x of [...(c.saleLines||[]),...(c.orderLines||[])]){const label=[x.article,x.description].filter(Boolean).join(' — ');if(label&&(!q||label.toLowerCase().includes(q)))seen.set(label,label)}$('#productSuggestions').innerHTML=[...seen.values()].slice(0,250).map(v=>`<option value="${escapeHtml(v)}"></option>`).join('')}
function updateYears(){const years=new Set();for(const c of Object.values(project.clients))for(const x of [...(c.saleLines||[]),...(c.orderLines||[])]){const y=lineYear(x);if(y)years.add(y)}const vals=[...years].sort((a,b)=>b-a);for(const id of ['yearFrom','yearTo']){const el=$(`#${id}`),cur=el.value,label=id==='yearFrom'?'Da anno':'A anno';el.innerHTML=`<option value="">${label}</option>`+vals.map(y=>`<option value="${y}">${y}</option>`).join('');el.value=cur}}
function render(){const all=Object.values(project.clients),view=filtered();fillSelect('#agentFilter',[...new Set(all.map(c=>c.agent).filter(Boolean))]);fillSelect('#provinceFilter',[...new Set(all.map(c=>c.province).filter(Boolean))]);updateYears();updateProductSuggestions();const visibleLines=view.flatMap(matchingLines);const filteredSales=visibleLines.filter(x=>x.kind==='sale').reduce((s,x)=>s+x.amount,0),filteredOrders=visibleLines.filter(x=>x.kind==='order').reduce((s,x)=>s+x.amount,0);$('#clientCount').textContent=view.length;$('#mappedCount').textContent=view.filter(c=>c.lat!=null).length;$('#ordersTotal').textContent=euro(hasTransactionFilter()?filteredOrders:view.reduce((s,c)=>s+c.orders,0));$('#salesTotal').textContent=euro(hasTransactionFilter()?filteredSales:view.reduce((s,c)=>s+c.sales,0));$('#status').textContent=statusText();renderList(view);renderMarkers(view)}
function fillSelect(sel,vals){const el=$(sel),cur=el.value,label=el.options[0].text;el.innerHTML=`<option value="">${label}</option>`+vals.sort().map(v=>`<option>${escapeHtml(v)}</option>`).join('');el.value=cur}
function renderList(items){$('#list').innerHTML=items.slice(0,400).map(c=>{const lines=matchingLines(c),fs=lines.filter(x=>x.kind==='sale').reduce((s,x)=>s+x.amount,0),fo=lines.filter(x=>x.kind==='order').reduce((s,x)=>s+x.amount,0);return `<article class="client" data-id="${c.id}"><h3>${escapeHtml(c.name||c.id)}</h3><p>${escapeHtml([c.city,c.province,c.agent].filter(Boolean).join(' · '))}</p><div class="badges">${(hasTransactionFilter()?fo:c.orders)?`<span class="badge order">Ordini ${euro(hasTransactionFilter()?fo:c.orders)}</span>`:''}${(hasTransactionFilter()?fs:c.sales)?`<span class="badge sales">Vendite ${euro(hasTransactionFilter()?fs:c.sales)}</span>`:''}${hasTransactionFilter()?`<span class="badge">${lines.length} righe prodotto</span>`:''}${c.lat==null?'<span class="badge missing">Da geocodificare</span>':''}</div></article>`}).join('');document.querySelectorAll('.client').forEach(x=>x.onclick=()=>openDetail(x.dataset.id))}
function renderMarkers(items){if(!markers||typeof L==='undefined')return;markers.clearLayers();for(const c of items){if(c.lat==null)continue;const cls=c.orders>0?'order':c.sales>50000?'top':'';const icon=L.divIcon({className:'',html:`<div class="marker-dot ${cls}"></div>`,iconSize:[18,18],iconAnchor:[9,9]});const m=L.marker([c.lat,c.lng],{icon,draggable:true}).addTo(markers).bindTooltip(c.name||c.id);m.on('click',()=>openDetail(c.id));m.on('dragend',e=>{const p=e.target.getLatLng();c.lat=p.lat;c.lng=p.lng;c.manualPosition=true;save()})}}
function openDetail(id){currentId=id;const c=project.clients[id];const years=Object.entries(c.saleYears||{}).sort((a,b)=>b[0]-a[0]).map(([y,v])=>`${y}: ${euro(v)}`).join('<br>')||'—';$('#detail').innerHTML=`<h2>${escapeHtml(c.name||c.id)}</h2><p>${escapeHtml([c.address,c.cap,c.city,c.province].filter(Boolean).join(', '))}</p><div class="detail-grid"><div class="detail-box"><b>${euro(c.orders)}</b><span>Ordini aperti</span></div><div class="detail-box"><b>${euro(c.sales)}</b><span>Vendite totali</span></div><div class="detail-box"><b>${escapeHtml(c.agent||'—')}</b><span>Agente</span></div><div class="detail-box"><b>${years}</b><span>Vendite per anno</span></div></div><div class="field"><label>Coordinate</label><div class="row"><input id="lat" value="${c.lat??''}" placeholder="Latitudine"><input id="lng" value="${c.lng??''}" placeholder="Longitudine"></div></div><div class="field"><label>Note locali</label><textarea id="note">${escapeHtml(c.note||'')}</textarea></div><div class="detail-actions"><button type="button" id="saveDetail" class="primary">Salva</button><a class="button" target="_blank" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(c.lat!=null?`${c.lat},${c.lng}`:[c.address,c.city,c.province].join(' '))}">Naviga</a></div><p><small>${c.phones?.map(escapeHtml).join(' · ')||''}<br>${c.emails?.map(escapeHtml).join(' · ')||''}</small></p>`;$('#saveDetail').onclick=()=>{const lat=parseFloat($('#lat').value),lng=parseFloat($('#lng').value);c.lat=Number.isFinite(lat)?lat:null;c.lng=Number.isFinite(lng)?lng:null;c.manualPosition=Number.isFinite(lat)&&Number.isFinite(lng);c.note=$('#note').value;save();$('#detailDialog').close()};$('#detailDialog').showModal()}
async function geocodeMissing(){const list=filtered().filter(c=>c.lat==null&&c.address&&c.city);if(!list.length)return alert('Nessun cliente da geocodificare nel filtro corrente.');if(!confirm(`Geocodificare ${list.length} indirizzi?`))return;let done=0;for(const c of list){$('#status').textContent=`Geocodifica ${done+1}/${list.length}: ${c.name}`;try{const q=[c.address,c.cap,c.city,c.province,'Italia'].filter(Boolean).join(', ');const res=await fetch(`https://nominatim.openstreetmap.org/search?format=json&limit=1&countrycodes=it&q=${encodeURIComponent(q)}`,{headers:{'Accept-Language':'it'}});const data=await res.json();if(data[0]){c.lat=Number(data[0].lat);c.lng=Number(data[0].lon)}}catch(e){console.warn(e)}done++;localStorage.setItem(DB_KEY,JSON.stringify(project));renderMarkers(filtered());await new Promise(r=>setTimeout(r,1100))}save();alert(`Geocodifica completata: ${done} indirizzi elaborati.`)}
function exportProject(){const blob=new Blob([JSON.stringify(project,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`maps-app-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
function fit(){if(!map)return alert('La mappa richiede una connessione Internet.');const pts=filtered().filter(c=>c.lat!=null).map(c=>[c.lat,c.lng]);if(pts.length)map.fitBounds(pts,{padding:[30,30]})}
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
$('#excelInput').onchange=e=>importFiles([...e.target.files]);$('#projectInput').onchange=async e=>{try{const p=JSON.parse(await e.target.files[0].text());if(!p.clients)throw 0;project=p;save();fit()}catch{alert('Progetto non valido')}};$('#exportBtn').onclick=exportProject;$('#fitBtn').onclick=fit;$('#geocodeBtn').onclick=geocodeMissing;['search','productSearch','agentFilter','provinceFilter','movementFilter','yearFrom','yearTo','onlyOrders','onlySales','onlyMissing'].forEach(id=>$(`#${id}`).addEventListener(['search','productSearch'].includes(id)?'input':'change',render));window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{deferredPrompt?.prompt();deferredPrompt=null;$('#installBtn').hidden=true};
load();initMap();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
